- Xendit/Xendit.swift
- XenditExample/XenditExample/Controllers/ValidateCardViewController.swift
We are not validating CVN correctly based on card type. Will cause an error when creating charge, better to handle it before creating the token
Change the CVN validation logic to check card type
> change cvn validation logic

- Xendit/Models/XenditCCToken.swift
- XenditExample/XenditExample/Controllers/CreateTokenViewController.swift
We need to return `masked_card_number` during tokenization
Add the response in model and example
> add masked card number to response

- Xendit.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- Xendit/Extensions.swift
- Xendit/Xendit.swift
implement xendit token in IOS SDK
> implement xendit token in IOS SDK

- Xendit/Xendit.swift
> fixing authentication path

- Xendit/Models/CardMetadata.swift
- Xendit/Models/XenditCCToken.swift
- XenditTests/StubResponses/credit_card_tokens.response
- XenditTests/XenditTests.swift
> [CC-3151] Added new card metadata model

- README.md
- Xendit/Models/XenditAuthenticatedToken.swift
- Xendit/Models/XenditAuthentication.swift
- Xendit/Models/XenditCCToken.swift
- Xendit/XDTCards.swift
- XenditExample/XenditExample/Controllers/CreateTokenViewController.swift
> [CC-3478] Deprecated token.metadata and introduced cardInfo

- Xendit/Models/XenditCardMetadata.swift
- XenditExample/XenditExample/Controllers/CreateTokenViewController.swift
> [CC-3569] Rename countryCode field to country in card_info

- Xendit.podspec
- Xendit/Models/XenditCardMetadata.swift
> [CC-4194] Added fingerprint to cardInfo model

- Xendit.podspec
- Xendit.xcodeproj/project.pbxproj
- Xendit/Models/AuthenticationData.swift
- Xendit/Models/CardData.swift
- Xendit/Models/DTOs/XenditAuthenticationRequest.swift
- Xendit/Models/DTOs/XenditCardData.swift
- Xendit/Models/DTOs/XenditTokenizationRequest.swift
- Xendit/Models/XenditAuthentication.swift
- Xendit/XDTCards.swift
- Xendit/Xendit.swift
- XenditExample/XenditExample/Controllers/CreateAuthentification.swift
- XenditExample/XenditExample/Controllers/CreateTokenViewController.swift
> Fixed examples to handle decimals

- Xendit.podspec
- Xendit.xcodeproj/project.pbxproj
- Xendit/Models/DTOs/XenditRetokenizationRequest.swift
- Xendit/XDTCards.swift
- Xendit/Xendit.swift
- XenditExample/XenditExample/Base.lproj/Main.storyboard
https://xendit.atlassian.net/browse/CC-7551
- Add new method for re-tokenization
> [CC-7551] Add retokenize

- Xendit.podspec
Remove build active arch to support build on arm.
> Remove build arch setting to support build on arm

- Sources/Xendit/XDTCards.swift
- Xendit.podspec
https://xendit.atlassian.net/browse/CC-7788
- Update zero amount validation
> [CC-7788] Update zero amount validation

- Sources/Xendit/Models/DTOs/XenditStoreCVNRequest.swift
- Sources/Xendit/XDTCards.swift
- Sources/Xendit/Xendit.swift
- Xendit.podspec
- Xendit.xcodeproj/project.pbxproj
https://xendit.atlassian.net/browse/CC-8199
- Add new function storeCVN
> [CC-8199] Add storeCVN function

- Package.resolved
- Package.swift
- Sources/Xendit/XDTApiClient.swift
- Sources/Xendit/XDTSentry.swift
- Sources/Xendit/Xendit.swift
- Xendit.xcodeproj/SentryPrivate_Info.plist
- Xendit.xcodeproj/Sentry_Info.plist
- Xendit.xcodeproj/project.pbxproj
- Xendit.xcworkspace/xcshareddata/swiftpm/Package.resolved
- https://xendit.atlassian.net/browse/CC-8173
> [CC-8173] Add Sentry SDK

- Sources/Xendit/Models/DTOs/XenditTokenizationRequest.swift
- XenditExample/XenditExample.xcodeproj/project.pbxproj
- XenditExample/XenditExample/Base.lproj/Main.storyboard
- XenditExample/XenditExample/Controllers/CreateTokenViewController.swift
add midLabel in json body for createToken
> Update XenditTokenizationRequest with midLabel

- README.md
- Sources/Xendit/XDTApiClient.swift
- Xendit.podspec
- Updated Readme
- Updated version to 3.8.2
> Bump release version

- Sources/Xendit/XDTCards.swift
> XDTCards: fix completion callback can be called multiple times

- Sources/Xendit/Utils/CreditCard.swift
- Sources/Xendit/XDTApiClient.swift
- Xendit.podspec
From this [thread](https://xendit.slack.com/archives/C06L0DLT48Z/p1716431731182719)
- Updated expiry month + year to use min comparison as current month/year
- Updated JCB detect func to same web FE
> Fixed hardcoded expiry year + month

- Sources/Xendit/Utils/CreditCard.swift
- Sources/Xendit/XDTApiClient.swift
- Xendit.podspec
> fix: card expiration validation

- Sources/Xendit/Models/DTOs/XenditAuthenticationRequest.swift
- Sources/Xendit/Models/DTOs/XenditCardHolderInformation.swift
- Sources/Xendit/Models/DTOs/XenditTokenizationRequest.swift
- Sources/Xendit/XDTCards.swift
- Sources/Xendit/Xendit.swift
- Add validation to remove empty string for cardholder information on token creation
> add validation to omit empty string from cardholder information

- README.md
- Sources/Xendit/Info.plist
- Sources/Xendit/Models/DTOs/XenditTokenizationRequest.swift
- Sources/Xendit/XDTApiClient.swift
- Xendit.podspec
- Add functionality to send SDK version
> Add functionality to send SDK version

- README.md
- Sources/Xendit/Info.plist
- Sources/Xendit/XDTApiClient.swift
- Xendit.podspec
Reverts xendit/xendit-sdk-ios-src#89
> Revert "Update version to 3.9.3"

- README.md
- Sources/Xendit/Info.plist
- Sources/Xendit/XDTApiClient.swift
- Xendit.podspec
- Xendit.xcodeproj/project.pbxproj
- Also update version to 3.10.1
> Fix missing XenditCardHolderInformation in project hierachy

- README.md
- Sources/Xendit/Info.plist
- Sources/Xendit/Models/DTOs/XenditCardHolderInformation.swift
- Sources/Xendit/Utils/CreditCard.swift
- Sources/Xendit/XDTApiClient.swift
- Sources/Xendit/XDTCards.swift
- Xendit.podspec
> Update empty checker for card data & force date checker to use Gregorian calendar

- Package.resolved
- Package.swift
- README.md
- Sources/Xendit/Info.plist
- Sources/Xendit/XDTApiClient.swift
- Xendit.podspec
- Xendit.xcodeproj/project.pbxproj
- Xendit.xcworkspace/xcshareddata/swiftpm/Package.resolved
- XenditExample/XenditExample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- [Slack discussion](https://xendit.slack.com/archives/C06L0DLT48Z/p1746780932486889)
- Also fix issue #102
> Update Sentry to 8.46.0
